### PR TITLE
Bump MSRV

### PR DESCRIPTION
**Pull request by zeenix**

### CODE REVIEW

**Review by haraldh — APPROVED** [review]

**Review by haraldh — APPROVED** [review]

**Comment by zeenix** [comment]
@haraldh Thanks. What's with the CI? :thinking:

**Comment by zeenix** [comment]
Not sure where these checks are coming from:

```
build (macos-latest, 1.63.0) 
build (ubuntu-latest, 1.63.0)
build (windows-latest, 1.63.0)
```

`rg 1.63 .github` in the repo returns nothing.

**Comment by zeenix** [comment]
> `rg 1.63 .github` in the repo returns nothing.

Ah, @haraldh you need to reselect the required workflows from the settings.

**Comment by haraldh** [comment]
Please gpg sign your commits :-)

**Comment by zeenix** [comment]
> Please gpg sign your commits :-)

Ughhh, ok.

**Comment by haraldh** [comment]
or, let me remove this hurdle, before development stalls

**Comment by zeenix** [comment]
> or, let me remove this hurdle, before development stalls

For this PR, I already signed the commits. Can you please approve again for the ci?

**Pull request merged**
